modLoader = "javafml"
loaderVersion = "[3,)"
license = "MIT"
issueTrackerURL = ""
logoFile = "pack.png"

[[mods]]
    modId = "ds_ender_dragonborn_addon"
    version = "0.0.1"
    displayName = "Play as Ender Dragonborn - Dragon survival addon"
    authors = "Shindryrth"
    description = " An addon for dragon survival mod that allows you to become an ender dragonborn. \n\n Extra Credits:\n lool8421, - Original Ender Dragon Addon"

[[dependencies.ds_ender_dragonborn_addon]]
	modId="neoforge" 
	type="required"
	mandatory = true
	versionRange="[21.1.186,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.ds_ender_dragonborn_addon]]
    	modId = "geckolib"
    	mandatory = true
    	versionRange = "[4.6,)"
    	ordering = "NONE"
    	side = "CLIENT"


[[dependencies.ds_ender_dragonborn_addon]]
    	modId = "dragonsurvival"
    	mandatory = true
    	versionRange = "[2.0.51,)"
    	ordering = "NONE"

[[dependencies.ds_ender_dragonborn_addon]]
modId = "ds_ender_dragon_addon"
mandatory = true
versionRange = "[1.2.2,)"
ordering = "NONE"

[[dependencies.ds_ender_dragonborn_addon]]
modId = "dragonborn_lib"
mandatory = true
versionRange = "[1.2.3,)"
ordering = "NONE"


